### ISSUE TITLE
Can you update to support the new Enable/Disable feature?

### ISSUE THREAD

**Issue by groty** [iqwunder/pihole_status#2]
Looks like the latest version of Pi-Hole has an Enable/Disable option.  It's available via the web interface..  No need to include server side code additions.

Can you update the plugin to leverage the new URL based command?

http://my-pi-hole/admin/?enable
http://my-pi-hole/admin/?disable

**Comment by iqwunder** [comment]
Thank you for the comment. I updated the plugin using the new url commands. 

But the server side code additions are still needed, because i have to ask for the status of pihole.
I changed the apiext.php script to ask for status and disable/enable the pihole, so there will only be one url to add.
The apiext,php can be copied to the directory /var/www/html/admin.
